//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 05:04:35 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://benchresources.in/cdm/Book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jersey.series.spring.hibernate.db.resources;
